version: '3'
services:
  mixtt:
    build:
      .
    image: mixtt_base
    privileged: true
    volumes:
     - ./etc/mixtt:/etc/mixtt
     - ./etc/faucet:/etc/faucet
     - .:/mixtt
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
    entrypoint: "/mixtt/docker/entrypoint.sh"
